### PR TITLE
change value of integer

### PR DESCRIPTION
**Pull request by pergolafabio**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by danielschramm** [comment]
Your patch does not decide whether a standard or extended ID is described by the number.

10std is not equal to 10ext on CanBus.

To really support extended IDs some more work on the code is needed.

Currently this repository does not really support extended IDs.

**Comment by pergolafabio** [comment]
> Your patch does not decide whether a standard or extended ID is described by the number.
> 
> 10std is not equal to 10ext on CanBus.
> 
> To really support extended IDs some more work on the code is needed.
> 
> Currently this repository does not really support extended IDs.

yeah, it was just quick and dirty, i am not a programmer at all , that all too advanced for me :)

**Comment by danielschramm** [comment]
@pergolafabio 
I'm just setting up a new set of hardware and then intend to do some experiments with Std/Ext ID separation.
I will keep you updated.
Perhaps you could support on finding out if it's possible to change the max value in this statement in dependency of an additional "IdType = StdID / ExtID" Flag.
"cv.GenerateID(CONF_CAN_ID): cv.int_range(min=1, max=4096)," 

Then I will have more time jumping in the C++ part of the job.

Thanks,

Daniel

**Comment by pergolafabio** [comment]
i really want to help, but i'm not a developer at all , i have no idea where i need to start?
i thought it was as easy to change the min/max value
since i did that change, and i loaded my own canbus esphome software, it just works, when i define that integer : 

```
    on_frame:
    - can_id: -2130641152
```

**Comment by danielschramm** [comment]
Adding the EXT Flag works for transmission and for receiving EXT Frames but it does not seem to be reliable for RX when STD 0x10 is defined also EXT 0x10 is received which must not be the case on a mixed segment.

I would prefer an extra config option for EXT frames instead of a bit in the ID which sometimes has to be negative while ID is normally an unsigned integer.
The issue is that depending on the flag the allowed range is different and the Coding rules from esphome request to better do the check in the init.py than in the C++ code.

**Comment by pergolafabio** [comment]
can i do something to test ?

**Comment by danielschramm** [comment]
> can i do something to test ?

https://github.com/danielschramm/esphome/tree/canbus_extid

just pushed this new branch.

This sends out an extended and a standard message on the same ID every second.
Receiving shows the difference in the logs but I did not currently test if can_ext_id parameter works on received data.

Thanks for doing some testing. I need some Sleep soon but I have 2 more free days for coding  ;-)

time:
  - platform: sntp
    on_time:
      - seconds: /1
        then:
          # 4 bytes ID CRCm 4 Bytes CAN ID
          - canbus.send:
              can_id: ${canId_Second}
              can_ext_id: True
              # Modul Schreibtisch
              data: [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]
          - canbus.send:
              can_id: ${canId_Second}
              can_ext_id: False
              # Modul Schreibtisch
              data: [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]

**Comment by pergolafabio** [comment]
ok, will do a test, but can you use the correct formatting? its easier for copying

**Comment by pergolafabio** [comment]
receiving this error on this line : 

```
    on_frame:
    - can_ext_id: -2130641152
```

error:

```
    Must be string, got <class 'NoneType'>. did you forget putting quotes around the value?.
    - [source /config/esphome/esp.yaml:45]
      
      Expected boolean value, but cannot convert 2130641152 to a boolean. Please use 'true' or 'false'.
      can_ext_id: 2130641152 [source /config/esphome/esp.yaml:45]
```

**Comment by danielschramm** [comment]
> receiving this error on this line :
> 
> ```
>     on_frame:
>     - can_ext_id: -2130641152
> ```
> 
> error:
> 
> ```
>     Must be string, got <class 'NoneType'>. did you forget putting quotes around the value?.
>     - [source /config/esphome/esp.yaml:45]
>       
>       Expected boolean value, but cannot convert 2130641152 to a boolean. Please use 'true' or 'false'.
>       can_ext_id: 2130641152 [source /config/esphome/esp.yaml:45]
> ```

I really need to do some doc updates tomorrow.
Just use the field "can_id" for the number and "can_ext_id" as bool to switch between std or ext id.
Code example is now better readable.

**Comment by pergolafabio** [comment]
yeah, sorry
i have now this : 

```
    can_ext_id: true
    #mode: NORMAL
    on_frame:
    - can_id: -2130641152
```

```
  can_ext_id: True
  on_frame:  [source /config/esphome/esp.yaml:46]
    - [source /config/esphome/esp.yaml:46]
      
      value must be at least 0.
      can_id: -2130641152 [source /config/esphome/esp.yaml:46]
```

**Comment by pergolafabio** [comment]
and this as a test :  (positive value)

```
    can_ext_id: true
    #mode: NORMAL
    on_frame:
    - can_id: 2130641152
      then:
```

error:


```
  can_ext_id: True
  on_frame:  [source /config/esphome/esp.yaml:46]
    - [source /config/esphome/esp.yaml:46]
      
      value must be at most 536870911.
      can_id: 2130641152 [source /config/esphome/esp.yaml:46]
```

**Comment by danielschramm** [comment]
Yes of course
2130641152 = 0x7EFF0100 is bigger than 29 Bit the extended Flag was included in that number.
Please try: 0x1EFF0100 = 520028416

**Comment by pergolafabio** [comment]
yeah, but i am just reading my canbus, thats the can_id that is presenting on the canbus, so to capture that frame, i need that high negavtive  value :-) ...

**Comment by pergolafabio** [comment]
i am not sending stuff on my canbus, just reading
My domotica system (lights in house) , is a canbus system, so i cam caturing wallswitches
so if i press a switch, i want to turn on a service in HA

**Comment by danielschramm** [comment]
> yeah, but i am just reading my canbus, thats the can_id that is presenting on the canbus, so to capture that frame, i need that high negavtive value :-) ...

Thanks for that hint.
As said receiving was not currently really tested.
Good to know with which IDs I can reproduce that output.

**Comment by pergolafabio** [comment]
you need to change that value again, so i can use a higher negative value ?

**Comment by danielschramm** [comment]
Hello @pergolafabio ,

now I implemented a proper range check for Standard and Extended IDs.
Also the logging is improved to provide clear hexadecimal ID representation.

Negative numbers are now completely eliminated.

I did not yet check the receive part of the code, but transmission, logging and range check seem to be ok.

**Comment by danielschramm** [comment]
Documentation is updated:
https://deploy-preview-823--esphome.netlify.app/components/canbus.html

I will just do some cleanup on the code to finish the task.

**Comment by pergolafabio** [comment]
Perfect, I saw new docs... Upon restart of esphome addon, it will automatically update to new version?

**Comment by pergolafabio** [comment]
nm, i see you are updating the canbus  branch

**Comment by danielschramm** [comment]
yes, the canbus branch is now rebased to todays esphome/dev and merged with the extid.

**Comment by pergolafabio** [comment]
tested, looks better now : 

```
[13:51:51][D][canbus:062]: received can message ext can_id=0x100ff00 size=4
[13:51:51][V][canbus:071]:   can_message.data[0]=01
[13:51:51][V][canbus:071]:   can_message.data[1]=45
[13:51:51][V][canbus:071]:   can_message.data[2]=02
[13:51:51][V][canbus:071]:   can_message.data[3]=00
```

i saw you closed the PR? whats wrong ?

**Comment by danielschramm** [comment]
I did a rebase ob the canbus branch to be in sync with todays esphome/dev but all changes from the last weeks to esphome/dev got part of the pull and throw errors.
I'm just doing the required lint tests and initiate a new pull.

**Comment by danielschramm** [comment]
Could you please check the changed code again.
I did some minor fixes.
The DOC is also updated.

**Comment by pergolafabio** [comment]
Did a restart of the add-on, all still working as expected now : 
a restart of the add-on always pull your lasst commits right?

```
[14:58:02][D][canbus:062]: received can message ext can_id=0x100ff00 size=4
[14:58:02][V][canbus:071]:   can_message.data[0]=01
[14:58:02][V][canbus:071]:   can_message.data[1]=45
[14:58:02][V][canbus:071]:   can_message.data[2]=02
[14:58:02][V][canbus:071]:   can_message.data[3]=00
```

**Comment by danielschramm** [comment]
Which "Addon" do you use?

**Comment by pergolafabio** [comment]
hassio/addon/a0d7b954_esphome

**Comment by pergolafabio** [comment]
and in config of the addon i enter : 

esphome_version: 'danielschramm:canbus'

**Comment by danielschramm** [comment]
I was not aware that that plugin can be used to do that. I'm just using my new version from the commandline.

I will will check it.

**Comment by pergolafabio** [comment]
i see in log, that it runs yours, but not 100% sure , if you change something it will always download the new files, i think so....


cont-init.d] 00-banner.sh: exited 0.
```
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] 30-esphome.sh: executing... 
[15:09:39] INFO: Installing esphome version 'danielschramm:canbus' (https://github.com/danielschramm/esphome/archive/canbus.zip)...
Collecting https://github.com/danielschramm/esphome/archive/canbus.zip
  Downloading https://github.com/danielschramm/esphome/archive/canbus.zip
Requirement already up-to-date: PyYAML==5.3.1 in /usr/local/lib/python3.6/dist-packages (from esphome==1.16.0.dev0)
Requirement already up-to-date: click==7.1.2 in /usr/local/lib/python3.6/dist-packages (from esphome==1.16.0.dev0)
Collecting colorlog==4.6.2 (from esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/4e/c8/c16d30bbed11a1722060014c246d124582d1f781b26f5859d8dacc3e08e1/colorlog-4.6.2-py2.py3-none-any.whl
Requirement already up-to-date: esptool==2.8 in /usr/local/lib/python3.6/dist-packages (from esphome==1.16.0.dev0)
Requirement already up-to-date: ifaddr==0.1.7 in /usr/local/lib/python3.6/dist-packages (from esphome==1.16.0.dev0)
Collecting paho-mqtt==1.5.1 (from esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/32/d3/6dcb8fd14746fcde6a556f932b5de8bea8fedcb85b3a092e0e986372c0e7/paho-mqtt-1.5.1.tar.gz (101kB)
Collecting platformio==5.0.3 (from esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/d8/7b/a79280396d25daa2ce01000d77c45dd4703764fcab4d0ae4a73c8f97f183/platformio-5.0.3.tar.gz (213kB)
Collecting protobuf==3.13.0 (from esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/30/79/510974552cebff2ba04038544799450defe75e96ea5f1675dbf72cc8744f/protobuf-3.13.0-cp36-cp36m-manylinux1_x86_64.whl (1.3MB)
Requirement already up-to-date: pyserial==3.4 in /usr/local/lib/python3.6/dist-packages (from esphome==1.16.0.dev0)
Collecting pytz==2020.4 (from esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/12/f8/ff09af6ff61a3efaad5f61ba5facdf17e7722c4393f7d8a66674d2dbd29f/pytz-2020.4-py2.py3-none-any.whl (509kB)
Requirement already up-to-date: tornado==6.0.4 in /usr/local/lib/python3.6/dist-packages (from esphome==1.16.0.dev0)
Requirement already up-to-date: tzlocal==2.1 in /usr/local/lib/python3.6/dist-packages (from esphome==1.16.0.dev0)
Collecting voluptuous==0.12.0 (from esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/d3/e9/861cec3f4da0728d9d085db9c338b598351cbacb10521c25f0857f55c6d4/voluptuous-0.12.0-py3-none-any.whl
Collecting ecdsa (from esptool==2.8->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/98/16/70be2716e24eaf5d81074bb3c05429d60292c2a96613a78ac3d69526ad2a/ecdsa-0.16.1-py2.py3-none-any.whl (104kB)
Requirement already up-to-date: pyaes in /usr/local/lib/python3.6/dist-packages (from esptool==2.8->esphome==1.16.0.dev0)
Collecting bottle<0.13 (from platformio==5.0.3->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/bf/44/aeafdd6ca05a8e1c3f91eeeb272a202d5cb1b3b23730a5ca686a81c48d24/bottle-0.12.19-py3-none-any.whl (89kB)
Collecting colorama (from platformio==5.0.3->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Collecting marshmallow>=2 (from platformio==5.0.3->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/28/02/547bdbd753be4e1977c212f17239045902cd3544060c33684d163aa12025/marshmallow-3.9.1-py2.py3-none-any.whl (46kB)
Collecting pyelftools<1,>=0.25 (from platformio==5.0.3->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/6f/50/3d7729d64bb23393aa4c166af250a6e6f9def40c90bf0e9af3c5ad25b6f7/pyelftools-0.27-py2.py3-none-any.whl (151kB)
Collecting requests<3,>=2.4.0 (from platformio==5.0.3->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/39/fc/f91eac5a39a65f75a7adb58eac7fa78871ea9872283fb9c44e6545998134/requests-2.25.0-py2.py3-none-any.whl (61kB)
Requirement already up-to-date: semantic_version<3,>=2.8.1 in /usr/local/lib/python3.6/dist-packages (from platformio==5.0.3->esphome==1.16.0.dev0)
Requirement already up-to-date: tabulate<1,>=0.8.3 in /usr/local/lib/python3.6/dist-packages (from platformio==5.0.3->esphome==1.16.0.dev0)
Collecting six>=1.9 (from protobuf==3.13.0->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==3.13.0->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/6d/38/c21ef5034684ffc0412deefbb07d66678332290c14bb5269c85145fbd55e/setuptools-50.3.2-py3-none-any.whl (785kB)
Collecting urllib3<1.27,>=1.21.1 (from requests<3,>=2.4.0->platformio==5.0.3->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/f5/71/45d36a8df68f3ebb098d6861b2c017f3d094538c0fb98fa61d4dc43e69b9/urllib3-1.26.2-py2.py3-none-any.whl (136kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.4.0->platformio==5.0.3->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/c1/6f/3d85f0850962279a7e4c622695d7b3171e95ac65308a57d3b29738b27149/certifi-2020.11.8-py2.py3-none-any.whl (155kB)
Collecting idna<3,>=2.5 (from requests<3,>=2.4.0->platformio==5.0.3->esphome==1.16.0.dev0)
  Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
Requirement already up-to-date: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.4.0->platformio==5.0.3->esphome==1.16.0.dev0)
Installing collected packages: colorlog, paho-mqtt, bottle, colorama, marshmallow, pyelftools, urllib3, certifi, idna, requests, platformio, six, setuptools, protobuf, pytz, voluptuous, esphome, ecdsa
```

**Comment by danielschramm** [comment]
I checked the docs and for my understanding it should always get the latest source on compiling.

**Comment by pergolafabio** [comment]
Then it works 😉

**Comment by danielschramm** [comment]
Do you think the docs are also easy to understand or do you have any suggestions for improvements?

**Comment by pergolafabio** [comment]
yeah, its quite ok
it was a hard time for me to understand, the canbus technology was quite new to me, now i understand

also thx a lot for your help

there are some guys on HA forums, that are going todo the same thing, i shared all info, they all have the same controllers as me

**Comment by danielschramm** [comment]
I'm working with CanBus for more than 20 years now and have my own home bus on CAN base but that was also missing HA integration til now.
I published the Hardware and Source of my system and just doing some rewrite for easy ESPhome interface (Repository on GitHub). Perhaps they could also be interesting for you.

**Comment by pergolafabio** [comment]
yeah, i just started with canbus, and was glad someone started with esphome :-)
also bought a canable.io , its still in shipping process 
but no idea if there is an integration to HA, didnt find any

**Comment by pergolafabio** [comment]
so what do you mean by home bus? what do you have in house then? also lights based on canbus? domotic system ?

**Comment by danielschramm** [comment]
I personally have only my window shades with this, but a friend also has some light applications in the same base.

http://pinguin.sauerland.de/din_rail.html#din_rail
https://github.com/danielschramm/din_rail_can

**Comment by pergolafabio** [comment]
Yeah, looks like mine controllers :-)

**Pull request closed without merging**
